New Default Command, align + drive
CSE-FortOsageCTC/5801_Inspire_2024 pull request #29
Opened 2024-01-24 01:01 UTC by T-Wezzy

2024-01-24 21:37 UTC, notrandomness submitted a review, later dismissed

2024-01-24 21:44 UTC, mxweII approved these changes, later dismissed

2024-01-24 21:57 UTC, Huntsmen requested changes
Just one thing to change and a small note thankies trevin :D

2024-01-24 21:57 UTC, Huntsmen commented on src/main/java/frc/robot/subsystems/DefaultTeleopSub.java
> +    public DefaultTeleopSub() {
Should be private because we don't want the constructor to be called else where.

2024-01-24 21:57 UTC, Huntsmen commented on src/main/java/frc/robot/commands/DefaultTeleop.java
> +        Pose2d botPose = s_DefaultTeleop.s_Limelight.getBotPose(); // gets botpose based on approximated position from limelight
Along the lines of getting the botpose from the position based on limelight. We should also add something in the future (just a thought for now) to get the botpose estimate from the swerve drive when the limelight is not visible or == 0. We can find a reference to that in NaviToPos (a navigation command).

2024-01-30 20:00 UTC, notrandomness requested changes

2024-01-30 20:00 UTC, notrandomness commented on src/main/java/frc/robot/AutoRotateUtil.java
> +   public void end(boolean isFinished) {
We will probably want to reset the PID in this method, that way the next time this instance is used, it won't have out-dated PID calculations. This also won't be called automatically by anything, so we will probably want to call it when the DefaultTeleop command ends.

2024-01-30 20:00 UTC, notrandomness commented on src/main/java/frc/robot/subsystems/Limelight.java
> +    public Pose2d getBotPose() {
We should document what this returns when no april tag is detected. I believe it will be a Pose2d with zeros for all values.

2024-02-01 00:09 UTC, notrandomness approved these changes

2024-02-01 00:09 UTC, merged